In [1]:
import numpy as np

a = [10,20,30,40]
type(a)

list

In [2]:
x = np.array(a)
print(x)

[10 20 30 40]


In [3]:
type(x)

numpy.ndarray

In [5]:
import numpy as np
a = [1,2,3,4]
b = [10,20,30,40]
y = np.aprray([a,b])
print(y)

AttributeError: module 'numpy' has no attribute 'aprray'

In [6]:
import numpy as np
a = [1,2,3,4]
b = [10,20,30,40]
y = np.aprray([a,b])
print(y)

AttributeError: module 'numpy' has no attribute 'aprray'

In [7]:
import numpy as np
a = [1,2,3,4]
b = [10,20,30,40]
y = np.array([a,b])
print(y)

AttributeError: module 'numpy' has no attribute 'aprray'

In [8]:
import numpy as np
a = [1,2,3,4]
b = [10,20,30,40]
y = np.array([a,b])
print(y)

[[ 1  2  3  4]
 [10 20 30 40]]


In [9]:
a = [1,2,3,4]
b = [10,20,30]
x = np.array([a,b])
print(x)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [10]:
x = np.array([1,2,3,4], dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [11]:
x = np.zeros((5,5))

In [12]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.random.choice([2,3,4,7,8,10])

np.int64(10)

In [17]:
np.random.randint??
np.random.choice([2,3,4,7,8,10])

np.int64(7)

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [18]:
x = np.eye(4, k = -1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [20]:
a = [3,6,9,12,15]
b = [1,2,3,4,5]
y = np.array([a,b])
print(y)
y.ndim

[[ 3  6  9 12 15]
 [ 1  2  3  4  5]]


2

In [21]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
x = np.arange(1,10).reshape(3,3)
print(x)
print(x[1:3,1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5]
 [8]]
